(defun both (tbl name)
    (cond ((null tbl) Nil)
          ((eql name (cdar tbl)) (caar tbl))
          ((eql name (caar tbl)) (cdar tbl))
          (t (f (cdr tbl) name))
    )
)

(defun con_by_cap (tbl name)
    (cond ((null tbl) Nil)
          ((eql name (caar tbl)) (cdar tbl))
          (t (con_by_cap (cdr tbl) name))
    )
)

(defun cap_by_con (tbl name)
    (cond ((null tbl) Nil)
          ((eql name (cdar tbl)) (caar tbl))
          (t (cap_by_con (cdr tbl) name))
    )
)