(defun select-between (lst num1 num2)
  (cond ((null lst) Nil)
        (t (reduce #'(lambda (x y)
                                 (cond ((and (> y num1) (< y num2))
                                        (cons y x))
                                       (t x)
                                 )
        ) lst :initial-value nil))
  )
)